### ISSUE TITLE
can`t change the style of label by using the demo and guide

### ISSUE THREAD

**Issue by JOJOyh** [google/blockly#4621]
**Where**

https://developers.google.cn/blockly/guides/configure/web/toolbox

**What**

  ![image](https://user-images.githubusercontent.com/13689315/107141627-f996fc80-6964-11eb-9c9f-605ceecb5575.png)

it does not work while i add the web-class for my label unless i disable this
```
.geras-renderer.classic-theme .blocklyFlyoutLabelText {
    /* fill: #000; */
}
```

**Old content**

**Suggested content**

**Additional context**

**Comment by BeksOmega** [comment]
Hello,

This looks like a simple [CSS specificity](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity) issue. You see, css styles are applied are given different "priority" based on their "specificity". This means that if one style is more specific than the other, the more specific style will get supplied.

In this case you're dealing with:
```css
.geras-renderer.classic-theme .blocklyFlyoutLabelText {
    fill: #000;
}
```
and 
```css
.myLabelStyle {
    fill: green;
}
```
As you can see, the first style has two classes, while the second only has a single class. This means the first style is more specific, which means it gets applied instead of the first one. You should be able to fix your custom style by doing this (if I'm remembering my css correctly hehe):
```css
.geras-renderer.classic-theme .blocklyFlyoutLabelText.myLabelStyle {
    fill: green;
}
```

---

We always appreciate getting questions, but in the future, please try to ask them on the [mailing list](https://groups.google.com/g/blockly). That way more people can see the question, and it keeps the github clean (just about development). So if you have any other questions, please ask [over there](https://groups.google.com/g/blockly)! I, and other people, will be happy to help :D

**Comment by JOJOyh** [comment]
thanks a lot，it works while i do this
``` css
<label text="123" web-class="myLabelStyle"></label>
```
```css
.blocklyFlyoutLabel.myLabelStyle>.blocklyFlyoutLabelText{
  font-style: italic;
  fill: green;
}
```
